Marketplace_webpage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('newsfeed/', include('newsfeed.urls')),
    path('', include('custom_admin.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_admin/urls.py
from django.urls import path

from newsfeed.views import profile
from . import views

app_name = 'custom_admin'

urlpatterns = [
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('users/', views.users, name='users'),
    path('delete_user/<pk>/', views.delete_user, name='delete_user'),
    path('messages/', views.messages, name='messages'),
    path('products/', views.products, name='products'),
    path('delete_product/<pk>/', views.delete_product, name='delete_product'),
    path('listing_reports/', views.listing_reports, name='listing_reports'),
    path('user_reports/', views.user_reports, name='user_reports'),
    path('delete_listing_report/<pk>/', views.delete_listing_report, name='delete_listing_report'),
    path('delete_message/<pk>/', views.delete_message, name='delete_message'),
    path('delete_user_report/<pk>/', views.delete_user_report, name='delete_user_report'),
]

main/urls.py
from django.urls import path
from . import views  # Import the views from the same directory

urlpatterns = list({
    path('', views.home, name='home'),  # Home page (index.html)
    path('register/', views.register, name='register'),  # Register page (register.html)
    path('contact/', views.contact, name='contact'),  # Contact page
    path('login/', views.login_view, name='login'),
})

newsfeed/urls.py
from django.urls import path, re_path
from Marketplace_webpage.views import home
from custom_admin.views import user_reports
from newsfeed.views import newsfeed, post_product, profile, edit_profile, logout_view, delete_listing, \
    category_selection, electronics, fashion, garden, sports, edit_listing, report_listing, report_user, search

app_name = 'newsfeed'

urlpatterns = [
    path('', newsfeed, name='newsfeed'),
    path('logout/', logout_view, name='logout'),
    path('post/', post_product, name='post_product'),
    path('profile/', profile, name='profile'),
    path('profile/<pk>/', profile, name='profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('delete-listing/<pk>/', delete_listing, name='delete_listing'),
    path('edit_listing/<pk>/', edit_listing, name='edit_listing'),
    path('report_listing/<pk>/', report_listing, name='report_listing'),
    path('report_user/<pk>/', report_user, name='report_user'),
    path('categories/', category_selection, name='category_selection'),
    path('search/', search, name='search'),
    path('electronics/', electronics, name='electronics'),
    path('fashion/', fashion, name='fashion'),
    path('garden/', garden, name='garden'),
    path('sports/', sports, name='sports'),
    path('user_reports/', user_reports, name='user_reports'),
]

newsfeed/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model


User = get_user_model()



class Product(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    mobile_number = models.CharField(max_length=20)
    location = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=50, choices=[('Electronics', 'Electronics'), ('Fashion and Beauty', 'Fashion and Beauty'), ('Home and Garden', 'Home and Garden'), ('Sports and Leisure', 'Sports and Leisure'), ('Others', 'Others')], default='Others')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_number = models.CharField(max_length=20)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username

def profile_view(request, pk):
    user = get_object_or_404(User, pk=pk)
    return render(request, 'profile.html', {'user': user})

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

from django.db import models
from django.contrib.auth.models import User

class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rated_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rated_user')
    rating = models.IntegerField()
    comment = models.TextField(blank=True)

    def __str__(self):
        return f'{self.user.username} rated {self.rated_user.username} {self.rating}/5'

class Report(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reason = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Listing Report'
        verbose_name_plural = 'Listing Reports'

    def __str__(self):
        return f"{self.product.title} listing reported by {self.user.username}"

class UserReport(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reported_user')
    reported_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reporter')
    reason = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} reported by {self.reported_by.username}"

newsfeed/forms.py
from .models import Product
from .models import Profile
from django import forms
from .models import Rating
from django.core.exceptions import ValidationError


class PostProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title', 'description', 'price', 'image', 'mobile_number', 'location', 'category')

    def __init__(self, *args, **kwargs):
        super(PostProductForm, self).__init__(*args, **kwargs)
        self.fields['mobile_number'].widget.attrs['placeholder'] = '+63 9123456789'

    def clean_mobile_number(self):
        mobile_number = self.cleaned_data['mobile_number']
        if not mobile_number.isdigit():
            raise ValidationError('Phone number must be a 10-digit number')
        if len(mobile_number) != 10:
            raise ValidationError('Phone number must be 10 digits long')
        if mobile_number[0] != '9':
            raise ValidationError('Phone number must start with 9')
        return mobile_number


class ProfileForm(forms.ModelForm):
    mobile_number = forms.CharField(max_length=10)

    class Meta:
        model = Profile
        fields = ('address', 'mobile_number')

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['mobile_number'].widget.attrs['placeholder'] = '+63 9123456789'

    def clean_mobile_number(self):
        mobile_number = self.cleaned_data['mobile_number']
        if not mobile_number.isdigit():
            raise ValidationError('Phone number must be a 10-digit number')
        if len(mobile_number) != 10:
            raise ValidationError('Phone number must be 10 digits long')
        if mobile_number[0] != '9':
            raise ValidationError('Phone number must start with 9')
        return mobile_number


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('rating', 'comment')
        widgets = {
            'rating': forms.Select(choices=[(i, i) for i in range(1, 6)])
        }

newsfeed/views.py
from custom_admin.views import is_staff
from .models import Product, User, UserReport
from .forms import PostProductForm
from django.contrib import messages
from .forms import ProfileForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Profile, Product, Report
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Rating
from .forms import ProfileForm, RatingForm
from django.db.models import Avg, Count

def logout_view(request):
    logout(request)
    return redirect('index', logout=True)

def newsfeed(request):
    products = Product.objects.filter(is_active=True).order_by('-created_at')
    return render(request, 'newsfeed.html', {'products': products})

def post_product(request):
    if request.method == 'POST':
        form = PostProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.category = request.POST['category']
            product.save()
            messages.success(request, 'Your product has been successfully listed!')
            return redirect('newsfeed:newsfeed')
    else:
        form = PostProductForm()
    return render(request, 'post_product.html', {'form': form})


@login_required
def profile(request, pk):
    if pk is None:
        pk = request.user.pk
    user = get_object_or_404(User, pk=pk)
    profile = user.profile
    is_owner = user == request.user

    # Move the ratings query to the top
    ratings = Rating.objects.filter(rated_user=user)

    # Calculate the summary ratings
    average_rating, star_equivalent_average_rating, num_ratings = get_rating_summary(ratings)

    if request.method == 'POST':
        if is_owner:
            edit_form = ProfileForm(request.POST, instance=profile)
            if edit_form.is_valid():
                edit_form.save()
                messages.success(request, 'Profile updated successfully!')
                return redirect('newsfeed:newsfeed')
        else:
            rating_form = RatingForm(request.POST)
            if rating_form.is_valid():
                rating = rating_form.save(commit=False)
                rating.user = request.user
                rating.rated_user = user
                rating.save()
                messages.success(request, 'Your review has been submitted successfully!')
                # Refresh the ratings query to include the newly submitted rating
                ratings = Rating.objects.filter(rated_user=user)
                # Recalculate the summary ratings
                average_rating, star_equivalent_average_rating, num_ratings = get_rating_summary(ratings)

    if is_owner:
        edit_form = ProfileForm(instance=profile)
        rating_form = None
    else:
        edit_form = None
        rating_form = RatingForm()

    products = Product.objects.filter(user=user, is_active=True)

    # Pass ratings and summary ratings to the template context in all cases
    return render(request, 'profile.html',
                  {'products': products, 'edit_form': edit_form, 'rating_form': rating_form, 'user': user,
                   'is_owner': is_owner, 'ratings': ratings, 'average_rating': average_rating,
                   'star_equivalent_average_rating': star_equivalent_average_rating, 'num_ratings': num_ratings})

def get_rating_summary(ratings):
    if ratings:
        average_rating = sum(rating.rating for rating in ratings) / len(ratings)
        if average_rating is not None:
            star_equivalent_average_rating = round(average_rating, 1)  # assuming 1 decimal place
        else:
            star_equivalent_average_rating = None
        num_ratings = len(ratings)
    else:
        average_rating = None
        star_equivalent_average_rating = None
        num_ratings = 0
    return average_rating, star_equivalent_average_rating, num_ratings

@login_required
def delete_listing(request, pk):
    listing = get_object_or_404(Product, pk=pk)
    if listing.user == request.user:
        listing.is_active = False
        listing.save()
        messages.success(request, 'Listing deleted successfully!')
        return redirect('newsfeed:profile', pk=request.user.pk)
    else:
        messages.error(request, 'You do not have permission to delete this listing.')
        return redirect('newsfeed:profile', pk=request.user.pk)
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully!')
            return redirect('newsfeed:newsfeed')
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'edit_profile.html', {'form': form})

@login_required
def edit_listing(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.user == request.user:
        if request.method == 'POST':
            form = PostProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid():
                form.save()
                messages.success(request, 'Listing updated successfully!')
                return redirect('newsfeed:newsfeed')
        else:
            form = PostProductForm(instance=product)
        return render(request, 'edit_listing.html', {'form': form})
    else:
        messages.error(request, 'You do not have permission to edit this listing.')
        return redirect('newsfeed:newsfeed')

@login_required
def report_listing(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.user == request.user:
        messages.error(request, 'You cannot report your own listing.')
        return redirect('newsfeed:newsfeed')
    if request.method == 'POST':
        reason = request.POST.get('reason')
        report = Report.objects.create(product=product, user=request.user, reason=reason)
        messages.success(request, 'Listing reported successfully!')
        return redirect('newsfeed:newsfeed')
    return render(request, 'report_listing.html')

@login_required
def report_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        reason = request.POST.get('reason')
        report = UserReport.objects.create(user=user, reported_by=request.user, reason=reason)
        messages.success(request, 'User  reported successfully!')
        return redirect('newsfeed:newsfeed')
    return render(request, 'report_user.html')

def category_selection(request):
    return render(request, 'category_selection.html')
def search(request):
    query = request.GET.get('q')
    products = Product.objects.filter(title__icontains=query)
    return render(request, 'search_results.html', {'products': products})

from django.shortcuts import render
from .models import Product

def electronics(request):
    products = Product.objects.filter(category='Electronics')
    return render(request, 'electronics.html', {'products': products})

def fashion(request):
    products = Product.objects.filter(category='Fashion and Beauty')
    return render(request, 'fashion.html', {'products': products})

def garden(request):
    products = Product.objects.filter(category='Home and Garden')
    return render(request, 'garden.html', {'products': products})

def sports(request):
    products = Product.objects.filter(category='Sports and Leisure')
    return render(request, 'sports.html', {'products': products})

@login_required
@user_passes_test(is_staff)
def user_reports(request):
    reports = UserReport.objects.all()
    return render(request, 'user_reports.html', {'reports': reports})

newsfeed/templates/category_selection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile - Marketplace</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
.category {
    display: block;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    text-align: center;
    transition: background-color 0.2s ease;
    text-decoration: none;
    color: #666; /* Change font color to grey */
}

.category:hover {
    background-color: #f7f7f7;
    text-decoration: none;
    color: #666; /* Keep font color grey on hover */
}
footer {
    position: absolute;
    bottom: 0;
    width: 100%;
    padding: 10px;
    text-align: center;
}

body {
    position: relative;
    min-height: 100vh;
    margin: 0;
    padding: 0;
}

main {
    padding-bottom: 50px; /* adjust this value to match the height of your footer */
}
header {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 100px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        footer {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 50px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
    </style>

    </head>
<body>
    <header>
        <div class="container">
            <h1 class="logo">Ecalp Techmar</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'newsfeed:newsfeed' %}"><i class="fas fa-home"></i> News Feed</a></li>
                    <li><a href="{% url 'home' %}" onclick="return confirm('Are you sure you want to log out?')">
    <i class="fas fa-sign-out-alt"></i> Logout
</a></li>

        </div>
    </header>

<section id="categories">
    <div class="container">
        <h2>Categories</h2>
        <div class="categories-grid">
            <a href="{% url 'newsfeed:electronics' %}" class="category">
                <i class="fas fa-mobile-alt fa-2x"></i>
                <h3>Electronics</h3>
                <p>Latest gadgets and electronics at unbeatable prices.</p>
            </a>
            <a href="{% url 'newsfeed:fashion' %}" class="category">
                <i class="fas fa-tshirt fa-2x"></i>
                <h3>Fashion and Beauty</h3>
                <p>Trendy and stylish clothing for all seasons.</p>
            </a>
            <a href="{% url 'newsfeed:garden' %}" class="category">
                <i class="fas fa-home fa-2x"></i>
                <h3>Home & Garden</h3>
                <p>Decor and furniture to make your house a home.</p>
            </a>
            <a href="{% url 'newsfeed:sports' %}" class="category">
                <i class="fas fa-book fa-2x"></i>
                <h3>Sports and Leisure</h3>
                <p>pang sports mg insert</p>
            </a>
        </div>
    </div>
</section>

    <footer>
        <div class="container">
            <div class="footer-content">
                <p style="text-align: center; width: 100%;">&copy; 2024 Ecalp Techmar. All rights reserved.</p>
            </div>
        </div>
    </footer>
</section>
</html>

newsfeed/templates/electronics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Newsfeed - Marketplace</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .product {
            display: inline-block;
            margin: 20px;
            width: 45%; /* Adjusted width to 45% */
            vertical-align: top;
            text-align: center;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .product:nth-child(odd) {
            background-color: #f7f7f7;
        }

        .product:nth-child(even) {
            background-color: #ffffff;
        }

        .product img {
            width: 200px;
            height: 200px;
            object-fit: cover;
            border-radius: 10px;
            margin: 0 auto;
        }

        .product h2 {
            margin-top: 10px;
        }

        .alert {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        .alert-success {
            background-color: #dff0d8;
            border-color: #d6e9c6;
            color: #3c763d;
        }

        .long-description {
            max-height: 100px; /* adjust this value to set the maximum height */
            overflow-y: auto;
            word-wrap: break-word;
        }

        .long-description.long {
            overflow: hidden;
            text-overflow: ellipsis;
        }

        .post-button {
            position: fixed;
            top: 20px;
            right: 20px;
            background-color: #2196F3;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            font-weight: bold;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

        .post-button:hover {
             background-color: #1A237E;
        }

        .post-button a {
            color: #fff;
            text-decoration: none;
        }

        .post-button i {
            margin-right: 10px;
        }
        header {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 100px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        footer {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 50px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
              footer {
  position: fixed;
  bottom: 0;
  width: 100%;
  background-color: #ccc; /* change to your desired color */
  padding: 10px;
  text-align: center;
}
                 .no-results {
            text-align: center;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1 class="logo">Ecalp Techmar</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'newsfeed:category_selection' %}"><i class="fas fa-th"></i> Categories</a></li>
                    <li><a href="{% url 'newsfeed:profile' request.user.pk %}"><i class="fas fa-user"></i> Profile</a></li>
                    <li><a href="{% url 'home' %}" onclick="return confirm('Are you sure you want to log out?')">
    <i class="fas fa-sign-out-alt"></i> Logout
</a></li>
                </ul>
            </nav>
            <button class="post-button">
              <a href="{% url 'newsfeed:post_product' %}">
                 <i class="fas fa-plus-circle"></i> Post a Product
              </a>
                </button>
        </div>
    </header>

<section id="electronics">
    <h2>Electronics</h2>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" style="text-align: center;">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="products">
        {% for product in products %}
            <div class="product">
                <img src='{{ product.image.url }}'>
                <h2>{{ product.title }}</h2>
                <p>Category: {{ product.category }}</p>
                <p class="description">{{ product.description|linebreaks|truncatewords:20 }}</p>
                <p>Price: {{ product.price }}</p>
                <p>Mobile Number: {{ product.mobile_number }}</p>
                <p>Location: {{ product.location }}</p>
                <p>Posted by: <a href="{% url 'newsfeed:profile' product.user.pk %}">{{ product.user.username }}</a></p>
                <p>Posted at: {{ product.created_at }}</p>
            </div>
        {% empty %}
            <p class="no-results">No listings posted in this category as of the moment.</p>
        {% endfor %}
    </div>
</section>

    <footer>
        <div class="container">
            <div class="footer-content">
                <p style="text-align: center; width: 100%;">&copy; 2024 Ecalp Techmar. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>

newsfeed/templates/post_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post a Product Listing - Marketplace</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>

.product-info p {
  font-size: 16px;
  margin-bottom: 10px;
}

.button-group .button {
  background-color: #2196F3;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.button-group .button:hover {
  background-color: #3e8e41;
}

        .container {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-bottom: none; /* Remove border bottom */
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 10px;
        }

        .form-group input, .form-group textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .form-group textarea {
            height: 100px;
        }

        .button {
            background-color:  #2196F3;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .button:hover {
            background-color: #3e8e41;
        }

        body {
            margin: 0;
            padding: 0;
            padding-bottom: 50px; /* Add padding to the bottom of the body */
        }
        .error-message {
    color: red;
    border: 1px solid red;
    padding: 5px;
    background-color: #ffcccc;
}

        footer {
            background-color: ;
            padding: 10px;
            text-align: center;
            width: 100%;
        }
        .post-product-box {
  background-color: #fff;
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  margin-bottom: 20px;
  text-align: center;
}

.post-product-box h2 {
  margin-top: 0;
  text-align: left;
}

.product-info .form-group {
  margin-bottom: 20px;
  display: inline-block;
  text-align: left;
  width: 80%;
  margin: 0 auto;
}

.product-info label {
  display: block;
  margin-bottom: 10px;
}

.product-info input, .product-info textarea {
  width: 100%;
  padding: 10px;
  margin-bottom: 20px;
  border: 1px solid #ccc;
  border-radius: 5px;
}

.product-info textarea {
  height: 100px;
}

.button-group {
  padding: 20px;
  border-top: 1px solid #ddd;
  text-align: center;
}

.button-group .button {
  background-color: #2196F3;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.button-group .button:hover {
  background-color: #3e8e41;
}
header {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 100px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        footer {
            background-image: url("{% static 'main/8422166.jpg' %}");
            background-size: cover;
            background-position: center;
            height: 50px;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1 class="logo">Ecalp Techmar</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'newsfeed:newsfeed' %}"><i class="fas fa-home"></i> News Feed</a></li>
                </ul>
            </nav>
        </div>
    </header>

<section id="post-product">
    <div class="container">
        <h2>Post a Product Listing</h2>
        <div class="post-product-box">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title:</label>
                    {{ form.title }}
                </div>
                <div class="form-group">
                    <label for="id_description">Description:</label>
                    {{ form.description }}
                </div>
                <div class="form-group">
                    <label for="id_price">Price:</label>
                    {{ form.price }}
                </div>
                <div class="form-group">
                    <label for="id_image">Image:</label>
                    {{ form.image }}
                </div>
                <div class="form-group">
                    <label for="id_mobile_number">Mobile Number (+63)</label>
                    {% if form.mobile_number.errors %}
                        <div class="error-message">
                            {{ form.mobile_number }}
                            <span>{{ form.mobile_number.errors }}</span>
                        </div>
                    {% else %}
                        {{ form.mobile_number }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="id_location">Location:</label>
                    {{ form.location }}
                </div>
                <div class="form-group">
                    <label for="id_category">Category:</label>
                    {{ form.category }}
                </div>
                <button type="submit" class="button">Post</button>
            </form>
        </div>
    </div>
</section>
    <footer>
        <div class="container">
            <div class="footer-content">
                <p style="text-align: center; width: 100%;">&copy; 2024 Ecalp Techmar. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>